version: '3'
services:
  ssii-postgresql:
    image: postgres:13
    volumes:
      - ssii_db:/var/lib/postgresql
      - ssii_data:/var/lib/postgresql/data
    networks:
      - back
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - ssii-postgresql
    networks:
      - back
volumes:
  ssii_data:
  ssii_db:

networks:
  back:

